# Generated by Django 5.0.6 on 2024-06-29 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamefolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="datePosted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
